# Generated by Django 5.0.1 on 2024-01-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
