# Generated by Django 5.0.1 on 2024-01-16 05:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_blog_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(default=12),
            preserve_default=False,
        ),
    ]
