# Generated by Django 5.0.1 on 2024-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paraph',
            field=models.TextField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
