# Generated by Django 5.0.1 on 2024-01-17 02:59

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_product_paraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paraph',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='paraph',
            field=models.TextField(),
        ),
    ]
