# Generated by Django 5.0.1 on 2024-01-17 03:37

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_blog_content_alter_blog_paraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
            ],
        ),
    ]
