# Generated by Django 5.0.1 on 2024-01-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_blog_content_alter_blog_paraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='paraph',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='paraph',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
