# Generated by Django 5.0.1 on 2024-01-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
