# Generated by Django 5.0.1 on 2024-01-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_blog_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Updates', 'verbose_name_plural': 'Updates'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text=' The recommended size is 120x120 pixels.', upload_to='products/img'),
        ),
    ]
