# Generated by Django 5.0.1 on 2024-01-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_blog_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text=' The recommended size is 600x300 pixels.', upload_to='products/img'),
        ),
    ]
