# Generated by Django 5.0.1 on 2024-01-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_product_image_height_product_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field='image_height', help_text='The recommended size is 600x300 pixels.', upload_to='products/img', width_field='image_width'),
        ),
    ]
